name: 'Gettext Validation Action'
description: 'Uses GNU gettext to verify that all .po files in a folder can be converted to .mo files.'
author: 'Tar-Minyatur'
inputs:
  folder:
    description: "Folder containing the .po files"
    default: ./
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.folder }}
